### ISSUE TITLE
iBank and UUID

### ISSUE THREAD

**Issue by Carton32** [iBa/iBank#21]
Hi,

Your plugin is used by tousands of players on my server. Thanks for that !

Will your plugin be updated to support UUID ?

Thank you.

**Comment by steffengy** [comment]
Currently not planning that, 
if you wish to support further iBank development, a donation is always very much appreciated.

**Comment by Carton32** [comment]
You know...I run a 700-1000 player a day server without asking anyone to pay something. I pay around 150$ per month just for the pleasure of running a community and for the pleasure of my players. I don't earn anything. Play.kingofkloug.com if you want to check if I say is true.

I run my server by passion and, nowadays, in the Minecraft world everybody is asking for money...it's sad. 

If you make a plugin UUID compatible and with a conversion tool for the SQLite db, I will donate 10$. Not before.

**Comment by steffengy** [comment]
Not saying I won't do it, just saying that unfortunately it is not on the top of my todo list.

Basically I'll do it if I get to do it, which at the moment is unlikely, 
because I currently am not planning to do the following:

- Build against SPIGOT (or whatever after bukkit is now used)
- Plan/Test Migration Logic
- Implement UUID Support (not much work)
- Test it
- Build it, maybe address other issues

Fortunately, it's open source, so maybe someone else
- even if i do not know, if iBank is actually still used *popularily*
- will look into it.

Sorry and hopefully it won't impact your server negatively

**Comment by Carton32** [comment]
I found someone in my community who did it. Not as good as an official release but it works.

Thank you for your answer.

**Comment by steffengy** [comment]
Nice that that worked for you :)

If you want official support, code-contributions are also always appreciated.
So if you wanted me to take a look at the changes, just submit a PR.

**Comment by Trojaner25** [comment]
https://github.com/iBa/iBank/pull/22

I manually updated it.
